name: Python lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: isort/isort-action@master
      with:
        sortPaths: "./mausignald ./mautrix_signal"
    - uses: psf/black@21.12b0
      with:
        src: "./mausignald ./mautrix_signal"
